<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur_control</name>
  <version>0.1.0</version>
  <description>The ur_control package</description>
  <author email="cristianbehe@gmail.com">Cristian Beltran</author>
  <maintainer email="cristianbehe@gmail.com">Cristian Beltran</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>control_msgs</depend>
  <depend>controller_manager_msgs</depend>
  <depend>effort_controllers</depend>
  <depend>joint_trajectory_controller</depend>
  <depend>robot_state_publisher</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>geometry_msgs</depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-pyquaternion</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
